### ISSUE TITLE
Tally skills in the mastery tree are not present in `skills.json`

### ISSUE THREAD

**Issue by iconmaster5326** [iconmaster5326/Chronomancer#5]
![image](https://user-images.githubusercontent.com/3768458/103099347-186f4880-45dc-11eb-83c8-21e19fc839ad.png)

They don't seem to be present in Chronicon's raw skill data, so I may have to come up with a hack to add them to `skills.json`. @gabriel-dehan, do you think that this is a problem on ChroniconDB's end, on Squarebit's end, or neither?

**Comment by gabriel-dehan** [comment]
I'll ask squarebits about it, I am adding it to the list :D

**Comment by iconmaster5326** [comment]
In 1.30.0, this issue has been resolved. However, all classes will have copies of all common mastery skills in 1.30.0, so I will need to update the UI to un-duplicate common mastery skills.

**Comment by iconmaster5326** [comment]
And done. Tally skills are now present.
