### ISSUE TITLE
Active skills don't have cooldown information

### ISSUE THREAD

**Issue by iconmaster5326** [iconmaster5326/Chronomancer#6]
How long the cooldown of an active skill is seems to be entirely absent from `skills.json`. @gabriel-dehan, do you think this is a problem with the data you get from Squarebit, or is it an issue with ChroniconDB?

**Comment by gabriel-dehan** [comment]
Can you confirm that some skills are really missing a cooldown? Because some skills definitely have a cooldown I've seen cooldowns in the file, but unsure if some skills are not missing some data. If that's the case I'll add it to the list of things to ask

**Comment by iconmaster5326** [comment]
Looking at `skills.json`, I do see some `cooldown` keys in there now. Then it must be that some skills lack cooldown information. I'll get a list of any I find to you.

**Comment by iconmaster5326** [comment]
As it turns out, this is an issue with ChroniconDB dataset parsing, and not us. Filing this issue with them and closing this one.

**Comment by iconmaster5326** [comment]
I was wrong! It was indeed a bug with Chronicon and not ChroniconDB. Squarebit found this issue and fixed it, so 1.30.0 should have all cooldowns present.
