### ISSUE TITLE
Active skills don't have tags

### ISSUE THREAD

**Issue by iconmaster5326** [iconmaster5326/Chronomancer#7]
By "tags", I mean things skills can be, such as base, sentry, bone, etc. We have skill families, but not all the possible tags a skill can belong to. The data is simply not present in `skills.json`.

@gabriel-dehan, do you think this is a problem with the data you get from Squarebit, or is it an issue with ChroniconDB?

**Comment by gabriel-dehan** [comment]
No, I don't have the tags in the original data, sadly, I am taking note of it to ask Squarebits

**Comment by iconmaster5326** [comment]
Tags will now be present in 1.30.0. Thanks, Squarebit, for the fix!

**Comment by iconmaster5326** [comment]
Tags are now in the dataset. When 1.30.0 rolls around, I can add them to the UI.
